# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: InstallFortifySCA@5
  inputs:
    InstallerPath: '/'
    VS2013: false
    VS2015: false
    LicenseFile: '/'
    RunFortifyRulepackUpdate: true
- task: FortifySCA@5
  inputs:
    runBuildTranslate: true
    applicationType: 'java'
    fortifyBuildId: '1.8'
    runFortifyRulepackUpdate: true
    runFortifyClean: true
    scaVerbose: true
    scaDebug: true
    runFortifyScan: true
    fortifyScanType: 'LocalScan'
# - task: SonarQubePrepare@4
#   inputs:
#     SonarQube: 'localSonarQ'
#     scannerMode: 'CLI'
#     configMode: 'file'
# - task: SonarQubeAnalyze@4
# - task: SonarQubePublish@4
#   inputs:
#     pollingTimeoutSec: '300'


